import type { Metadata } from 'next';
import './globals.css';
import { Navigation, Footer } from '../components/shared';

import { Inter as FontSans } from 'next/font/google';

import { cn } from '@/lib/utils';
import styles from './styles.module.css';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
        <Navigation></Navigation>
        <div className={styles.content}>{children}</div>
        <Footer></Footer>
      </body>
    </html>
  );
}
