import type { Metadata } from 'next';
import './globals.css';
import { Navigation, Footer } from '../core/components';

import { Inter as FontSans } from 'next/font/google';

import { cn } from '@/lib/utils';
import styles from './styles.module.css';
import { Keycloak } from '@/src/core/providers/Providers';
import SessionGuard from '@/src/core/providers/SessionGuard';
import { StoreProvider } from '../core/providers/StoreProvider';
import { ThemeProvider } from '../core/providers/ThemeProvider';
import { ProvidersAll } from '../core/providers/providers-all';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
        <Keycloak>
          <SessionGuard>
            <StoreProvider>
              <ProvidersAll>
                <ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
                  <Navigation></Navigation>
                  <div className={styles.content}>{children}</div>
                </ThemeProvider>
                <Footer></Footer>
              </ProvidersAll>
            </StoreProvider>
          </SessionGuard>
        </Keycloak>
      </body>
    </html>
  );
}
